name: '$(Date:yyyyMMdd).$(Rev:r)'

trigger:
- main

variables:
  buildConfiguration: 'Release'

pool:
  name: 'Self Agent'

stages:
  - stage: Build
    displayName: Build testapp
    dependsOn:
    jobs:
    - job: Build
      displayName: 'Build testapp'
      steps: 
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: 'aspnetcorereactspa.csproj'
          arguments: '--configuration $(buildConfiguration) --output $(Build.BinariesDirectory)/$(Build.BuildId)'
          modifyOutputPath: false
      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.BinariesDirectory)/$(Build.BuildId)'
          ArtifactName: 'drop-$(Build.BuildId)'
          publishLocation: 'Container'
